# Site
name: "ApprenticeDiary"
title: "Apprentice Diary"
description: "Apprentice Diary's blog."
logo: "assets/images/favicon/favicon-32x32.png"
favicon: "assets/images/favicon/favicon-32x32.png"
baseurl: /
# google_analytics: ""
# disqus: ""
# mailchimp-list: ""
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Elena:
    name: Elena
    display_name: Elena
    gravatar:
    email: apprenticediary@gmail.com
    description: "Author of ApprenticeDiary blog."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
